server:
  port: 9000
spring:  application:    name: RIBBON-SERVICE  
eureka:  client:    service-url:      default-zone: http://localhost:8761/
      
#<client>.ribbon.*
#ORDER-SERVICE:
#  ribbon:
#    listOfservers: localhost:8083,localhost:8086,localhost:8087
#  eureka:
#    enabled: false
           
    
